### ISSUE TITLE
Stopped merging

### ISSUE THREAD

**Issue by rand0mka** [AxelBjork/Rush-Royale-Bot#19]
Sometimes bot stopping merging pawns, but he has options
![image](https://user-images.githubusercontent.com/20513968/183481327-5e05e29e-3dbc-4b22-b20b-9ba4e40d0591.png)

**Comment by AxelBjork** [comment]
So

Bombardier and chemist (except highest) should be added as high priority merges and basically merge them right away, everything else should wait until there is 2 or less empty spots on board before merging any rank 1&2s. If the board is full it's supposed so merge units of any ranks except the dps units.

I have also seen that when the bots get into this "Full Grid - Merging" state it stops merging.

**Comment by AxelBjork** [comment]
This was tricky but there was bug when the bot tried to remove a unit entry which did not exist from the merge series (bottom left in gui).

Instead of returning the same series (nothing to be removed) it returned a empty series instead (bottom right in gui).

This line change fixes this issue: https://github.com/AxelBjork/Rush-Royale-Bot/pull/39/commits/57da357693b1020844d4a541b0c53f663f811083#diff-d6039c514e3846132c5e6499d71a16ebaa53a73fda52e87903a806f874d0622fR612
