### ISSUE TITLE
Bot stuck on "lost, waiting"

### ISSUE THREAD

**Issue by iOZ06** [AxelBjork/Rush-Royale-Bot#21]
Finally got it installed and configured right, started a quick test run and the bot get stuck on "lost, waiting" for forever. Is this a bug, or do I have something set up wrong?

[18:05] Started bot!
[18:05] Selected units: reaper, hex, executioner, demo, summoner
[18:05] PVE is set to True
[18:05] Bot mainloop started
[18:05] lost, waiting

**Comment by AxelBjork** [comment]
It could be a graphics option in Bluestacks which is causing the bot not to recognize things.

The resolution also has to be 1600 x 900 (or none of the references will match), that seems to have disappeared from the Readme.

Otherwise check if the bot_feed image looks ok, the bot is able to navigate to the battle screen, you can also try to run the Scrcpy.exe in the bot folder to see if it looks ok.

**Comment by iOZ06** [comment]
Seems to be somewhat working now with that resolution set (had it on 1920x1080 before). Closing as resolved.
