### ISSUE TITLE
✨ 'Start bot' should open Bluestacks 5 and open Rush Royale

### ISSUE THREAD

**Issue by Hona** [AxelBjork/Rush-Royale-Bot#33]
If not open

**Comment by AxelBjork** [comment]
I just noticed the bot fails to launch the game with the gui because it doesn't wait long enough anymore. It will still do it correctly if you wait out the 50 tries but should be easy to fix the startup.

About the bot launching Bluestacks, the bot doesn't interact at all with Bluestacks currently and it only have to be launched once so it seems unnecessary to add it. Some people may also want to run multiple Bluestacks instances so leaving up to the user I think is best for now.

**Comment by Hona** [comment]
I agree - closing this :)
