### ISSUE TITLE
Full card support

### ISSUE THREAD

**Issue by dracco1993** [AxelBjork/Rush-Royale-Bot#44]
I've recently had issues with the bot detecting `reapers`, as well as there being no images/training for several other cards.

1) Do you have plans to add all of the current cards?
2) Do you have a method for adding new cards that I could follow to get them added?  If so, I would happily add them and put in a PR.

**Comment by dracco1993** [comment]
I haven't gone through an extensive list, but `frost` and `boreas` both aren't included.  I can go through the list later this evening and figure out what all units are missing.
I've pulled a couple of the images already from the `OCR_input` folder; is there any model retraining that has to happen after I put those images in the `all_units` folder?

**Comment by AxelBjork** [comment]
Frost, boreas I didn't have when adding all. I think Minotaur, spirit master, robot are the only other ones missing.

Basically just throw all the units into a deck and get a image with them at rank 1.

```
import cv2

def crop_img(input, x, y, dx, dy, name='icon.png'):
    # Load screen
    img_rgb = cv2.imread(input)
    img_rgb = img_rgb[y:y + dy, x:x + dx]
    cv2.imwrite(name, img_rgb)
    img_rgb = cv2.cvtColor(img_rgb, cv2.COLOR_BGR2RGB)

name = 'tesla.png'
crop_img('OCR_inputs/icon_9.png',17,15,90,90,name)
```
Is the code I use for cropping, if it's just your own installation it might work if you just throw in the raw image. All the unit recognition is doing is looking at the most common pixel value in each OCR image and comparing it to the reference with some mean square loss so no training.

The rank prediction model generally works well with all units and doesn't need updating.

If you have correctly cropped images you can create PR, otherwise just upload the raw images of the units and I can crop and add them.

**Comment by dracco1993** [comment]
@AxelBjork see linked PR  🙂
