### ISSUE TITLE
OS error.

### ISSUE THREAD

**Issue by T9es** [AxelBjork/Rush-Royale-Bot#6]
Did everything as specified, getting this error on repeat: 

CalledProcessError: Command 'C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\adbutils\binaries\adb.exe -s emulator-5554 push C:\Users\AppData\Local\Programs\Python\Python39\Lib\site-packages\scrcpy\scrcpy-server.jar /data/local/tmp/' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

OSError: [Errno subprocess] C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\adbutils\binaries\adb.exe -s emulator-5554 push C:\Users\AppData\Local\Programs\Python\Python39\Lib\site-packages\scrcpy\scrcpy-server.jar /data/local/tmp/: "adb: error: failed to get feature set: device 'emulator-5554' not found\r\n"

Not sure how to fix this. Went through google for solid 1-2 hours, and could not manage to find any solid fix.

**Comment by AxelBjork** [comment]
That looks like it's gotten pretty far. It just looks like Scrcpy can't find Bluestacks.

You could try to first just get Scrcpy running. I use the prebuilt archive from their github.

For Bluestacks version 5.3 or less it should always be emulator-5554 and Scrcpy finds it automatically. Newer versions seems to randomize port on startup and it needs to scan for a few seconds to find it. 

If you go in Bluestacks advanced settings and it says 127.0.0.1:5555 it should be just to launch Scrcpy from the windows executable. Otherwise you can open a command line and type in,

{Scrcpy path}/scrcpy - s 127.0.0.1:xxxxx

That should launch it correctly.

If you had to type the port make sure you set `static_adb_port = False` in the bot config.ini file. Also make sure that the Scrcpy path is correct.

**Comment by T9es** [comment]
Right, got it to run, although it was not as easy as it was supposed to be. Had to manually add adb host, after that edit the code in the bot file to launch the localhost... and that's about it. Got it running, so glad I finally got it working
