### ISSUE TITLE
Problems with starting floor 3

### ISSUE THREAD

**Issue by T9es** [AxelBjork/Rush-Royale-Bot#8]
I've tested around the bot. In game it works just fine, although for some reason it has problems loading in floor 3. It just opens coop and backs out. Is that an actual issue, or is this just on my end?

**Comment by T9es** [comment]
Small edit here: The bot seems to scroll UP instead of down. That's the reason it gets stuck

**Comment by T9es** [comment]
![image](https://user-images.githubusercontent.com/107748212/181043080-eec36ed6-5164-4823-957f-a949024ecfa3.png)

This seems more like an issue with scrcpy, although I was not successful in trying to find a solution as of yet. Can't find any commands for scrcpy that would do the trick. Changing the device also does nothing

**Comment by AxelBjork** [comment]
I remember floor 3, 6, 9 are awkward to select due to the scrolling needed. Right now it just expands the chapter and clicks floor button using an offset from the chapter bar.

https://github.com/AxelBjork/Rush-Royale-Bot/blob/25e8b584463baddcd3ac2aae4cb7a0e2cb2c31cb/Src/bot_core.py#L310

Since they're not that optimal to farm I don't think it's that important to get them working.

As for Scrpy, it does look weird, I've had some similar issues with the screen in scrcpy being upside down on certain computers.

What seems to fix it is changing Bluestacks graphic options.
(Graphics) Graphics engine mode: Compatibility
(Graphics) Graphics renderer: OpenGL
(Graphics) Interface renderer: Auto
Also make sure resolution is 1600 x 900, pixel density 240 dpi

Bluestacks 5 version 5.3 or later should be good.

**Comment by T9es** [comment]
Yup, got it running. Thank you, have been looking around to fixing the issue from the code side. Did not even think that this could be a bluestacks graphics option bugs.
